language: node_js
node_js:
    - node
    - lts/*
cache:
    directories:
        - "~/.npm"
        - ".jest"
before_script:
    - npm install -g npm@latest
script:
    - npm ci
    - npx jest --ci
jobs:
    include:
        - stage: deploy
        node_js: lts/*
        script:
            - npm ci
            - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            - npx expo publish --non-interactive
env:
    global:
        - secure: JCB3PKP1+uTinnhtUJPyJZHJ6gI0yZVIqpONq7Bbg3F3/E6mVAy4fvqjDhx0/0ljNpJQ+4Q3U72pxc8SOkczMXnvikevhX71Qlkzj/UqNx22tVqAJkZeLwlJmCwBd+OIoISPGQTU+LaT+Qq7pBY7/qSlJzjYpTA3IfKiksNYxzLoDN0B3x/OJCw1Mzs7Bh5P5S1dQ91Fn8o7sdBO76Jbx94MwFZ5RdyzRsiJncdDAFSH5sU3KYzGDnBn8Pk5CvnlfZWnuRRsifJyXnyD8WBMkEwClJeSf4SlRinHbRN8wOZXEqKhGT2SNB0VY3aa1uHrIbKmY4PZOFIf3DdGMUF+hYa3yj6WykyE93Fv2SxXmnP50cYvi+cumqpNn2jAUu4yT22HfuqRABpO4GtMS8bPsAUnlhfSyTfcvczTwySxtOrUyR7iJz6IKU8NXo6/RRbL/NyrsVdXovsb86WA1Rps4K/bVeG1UvtuynTQQyycAx2PZ8FxpVMbswLHJFKSVSpQQxs/tKquOFxcjj6pHiUHUybk0WTx/SrzzpyLCe/5lYr6J3ZTOBGVYYvOk5vp4mufAq+yikr/QCNVaViiRonb0GyLRWOimiUzVbr7B6eqE3Z9ey3I9HMyw8qw1XG1NAQ5OpbjaQVi6+vTV7e3zyXGcRaxxTtqZVfljDu524XbK5A=
        - secure: T8lN8Av2QpvxgEyzeKkeDNE/r1VJNgv7vgUZr8fur14I1K1GvcimMWoet8lnT8zn82uhxSdkQC05T0rbwq8Xt6g02SZDcYs2eBA0s5ChuiWSzbp3RbQA3VSf2COr6i9C2cRXapf7L2+cLr/DrJ4yVuofntNeaU/OjbxWyw8Q4d4n5lgee5jI1uHXYdzO/raQXJEzD6UL541Xg/k7RQYN7X0bAboW78AwxOiSJUSohySm2uf6/WP4+MPq00ii5ZIelbibRNHuLyuFsMuuyf1DsDeQoAmjv2ysDZy/O91TPWkSVpiss6XGsDsfqqutmJBYF8ipQ2wUjL4s4X7qzsZHup3qXQze26W48SpKqdp7si2Vq5WgSOZQE9x7W+HEcu5zTwr5Tr6mAoZhf/EHpA1+etq2ZZt1V2s+eNIQlt5XQl2pOBOkDfzX7vQz2tLE8nUIHVH/UIZhvMWJbWhC92H//k+d8mOmcxmT6MAPKywa1WbvSsr6Ymm6MicXXygXbwEovSeV7DVMPTuVxQ0b3zKDqO/2fR+5z0H2kIo52+1SKK2s+iefPeABbz0rb4Q+UAzGbcPeQTh/BMDctitkv3crJRBvM8YJtH7AkFgK5YWgmlBgphugdO/OTsVyXyAY5ukyVFA/ZzS1gkueXqTmsVKgghS1LDJYx8fMwDYfQTUUJO0=
