language: node_js
node_js:
- node
- lts/*
cache:
  directories:
  - "~/.npm"
  - ".jest"
before_script:
- npm install -g npm@latest
- npm install -g expo-cli@latest
- echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
script:
- npm ci
- npx jest --ci
jobs:
  include:
  - stage: deploy
    node_js: lts/*
    script:
    - npm ci
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --release-channel develop --non-interactive
env:
  global:
  - secure: VbAkyORC3Tus7WxXldINpy5HQb16Q2KiPzzvyJvZTMEOvdc4yLIbfPEQ4nI9rSEOMNZ0Z7XGRcWSGBGSRMasjwsIpaBR5nFGGxuH1/dMv2CjezDLfbm6+vO0lveEcUuUf8T3HS/y8MtkmqtKKOG9thEBJRIqHZHnm25ZG2opRlruBkXiQH7qp2zOata9TxeASmiDq+it9QTxXqJVHPkJVGS4gShS276hPRsrQ12yHP0n8OcwkVo44TlqT+uV4z7emJZhM6JP7DdKOWY9cDlel5fIYj9/VLaAW+hnKz3Kdb8w06Oeuhy0YrbVufv8rmwkpxu5HQJAWQjpL8tl6ijLhiKlBNRMfYiIi+qdyYR2sumHrLAHoUbMqRmloZkVM1zd5qYeURckeVqjMB7AB0INqbq0W1Im65yjHTTN/7pErEfYzQ/eNPVQkkIHMZeg8RyoueZeSU0ksXSzEig8yKvqdK/nqaG6q/EIXx2LYVTFLi6Y30UGjjMwqeMyvWkIjARqAlMukylo1UkMhz4b4EnP7PxTokcHxj9ydKP0vUUnBplvTj+R4Q4vA7DP7ORf+ZETzZoL97VDLggvjnpChHy3tUb7n8HrUIWI28MyZ0/+Itzv/4sj1srUm/j+rDMeTatuauVFOPSTPde5i2h0OpNtKkMlEXAciTHtjGjMCUiycyM=
  - secure: OnVt29/xmY3nNQe7q3ZJND1aDCgwIfhhM8+PguPMMUEptY6dFqZ9V9QENUUBOfzPvb2i6uHqxQEwF5eLk5yOIOZmhxg6Kj8vy4aiHiRezNXHfvVDiIRFixUSwFyv9LdTNzSfjfmrwhEchjR5/NE9NP3vCvaPrd0ztoeE8XtfHXo11nPjeH1BNbZVH2OGwnpO/Gc85o1IDPWsnlyPI/wHeT4fG4en2PBeBRSl1w2QzeXEOBCVPKqpVOptzx6aHpYuNrBwgGuuikkiATkahbC9PElQY29xTyB60C4jaS82AK5VhZv6FqXg13aEO5TKSn36hR29UnY4VtsAmVR7fae1kfy8OQKKrut87Xb6f35PJSWSlhHNZzx0bYYyT1croe1KxHfhNwX2Gb9ectMttgDRuMnonRMFJPgnZIF0WTbvz67hIGSJK2pG2dgg1qulBg67s88xTBw94/3J3zXdnwQo1tSmhB391SZg9aRaBxzoqhq46FC81b6QsDrw/G6baEepE0V/mAYq1Ez6dhAka7iIGQ3BdeuWvUFIGWW6Ibp7HJ7cfuNn4L9vppCel/uPyQyLIuukoIABAFdEEPyI896PWBG38jpHVyY1axun7W+Yo5W71qkU3VFDuQ7JdOa8O6cfGIxyEwxaaxWz/efZUf0nSNWhiUW2CpAp4KIKHcUh9Ow=
